version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: vehicle_form_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend/vehicle-model-user-form
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_NAME: vehicle-model-user-form
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vehicle_form_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      LOGGING_LEVEL_COM_EXAMPLE_VEHICLE: DEBUG
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG
      SERVER_PORT: 8080
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:80" 
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080  

volumes:
  postgres_data: